"""remove adm

Revision ID: 187565e29c44
Revises: 1c20611c2d7a
Create Date: 2025-10-27 21:08:23.962294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '187565e29c44'
down_revision: Union[str, Sequence[str], None] = '1c20611c2d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('admin', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
